apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::699313006804:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FB4CXHP09CHF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::699313006804:role/UdacityFlaskDeployCBKubectlRole
      username: build
    
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-13T16:04:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "862"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c53f9de3-67b6-4969-835a-4251f4fd66e5
